# configure hydra to change the working directory
hydra:
  run:
    dir: outputs/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true

size: 512
model_version: "1.5"
model_name: dreamlike-art/dreamlike-photoreal-2.0
negative_prompt: lowres, bad anatomy, bad hands, cropped, worst quality
sample_prompt: yes
n_images: 4
n_rounds: 3
num_prompts: 1000
denoising_steps: 20
guidance_scale: 6
prompt_dropout: 0.0
use_pos_feedback: yes
use_neg_feedback: yes
feedback:
  start: 0.0
  end: 0.8
  min_weight: 0.0
  max_weight: 0.3
  neg_scale: 0.5
  warmup_power: 1
global_seed: 0
image_seed: null
liked_images: []
disliked_images: []
output_path: images

# For loading the Human Preference Score LoRA weights, set null to not use them
lora_weights: null  # resources/hps_lora/adapted_model.bin
topk: 0